namespace Apps.Shopify;

public enum TranslatableResource
{
    COLLECTION,
    COOKIE_BANNER,
    DELIVERY_METHOD_DEFINITION,
    EMAIL_TEMPLATE,
    FILTER,
    LINK,
    METAFIELD,
    METAOBJECT,
    ONLINE_STORE_ARTICLE,
    ONLINE_STORE_BLOG,
    ONLINE_STORE_MENU,
    ONLINE_STORE_PAGE,
    ONLINE_STORE_THEME,
    ONLINE_STORE_THEME_APP_EMBED,
    ONLINE_STORE_THEME_JSON_TEMPLATE,
    ONLINE_STORE_THEME_LOCALE_CONTENT,
    ONLINE_STORE_THEME_SECTION_GROUP,
    ONLINE_STORE_THEME_SETTINGS_CATEGORY,
    ONLINE_STORE_THEME_SETTINGS_DATA_SECTIONS,
    PACKING_SLIP_TEMPLATE,
    PAYMENT_GATEWAY,
    PRODUCT,
    PRODUCT_OPTION,
    PRODUCT_OPTION_VALUE,
    SELLING_PLAN,
    SELLING_PLAN_GROUP,
    SHOP,
    SHOP_POLICY
}